
[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | venv
  | env
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''
line-length = 90


[tool.isort]
profile = "black"

# optional groups
[tool.poetry.group.dev]
optional = true

[tool.poetry.group.test]
optional = true

[tool.poetry.group.doc]
optional = true